/**
 * 雷达指挥室（radar-lab）—— 紧凑自包含语料（~12 帖，混合来源/评论深浅）。
 * 给任务挂真实内容；world 把前若干条作「已采集」、其余作「待发现」池（discover 从中发现新帖）。
 */
import type { Comment, Post } from './types';

const c = (author: string, score: number, depth: number, body: string, children?: Comment[]): Comment => ({
  author,
  score,
  depth,
  body,
  children,
});

export const POSTS: Post[] = [
  {
    id: 't3_saas01',
    source: 'reddit',
    channel: 'r/SaaS',
    title: 'How do you handle churn when customers "just forget" to use the product?',
    body: 'We have decent activation but 6-month churn is brutal. People sign up, use it twice, then ghost. Tried emails, in-app nudges… nothing sticks. What actually moved the needle for you?',
    author: 'indie_maker_jo',
    score: 312,
    numComments: 84,
    commentDepth: 3,
    ageMinutes: 95,
    comments: [
      c('growthq', 41, 0, 'Onboarding that ties the product to a recurring workflow. If it is not in their weekly routine, you lost.', [
        c('indie_maker_jo', 12, 1, 'Any concrete example of "tying to a workflow"?', [
          c('growthq', 18, 2, 'We send a Monday digest they actually need; the digest links back into the app. Usage doubled.'),
        ]),
      ]),
      c('saas_dan', 23, 0, 'Usage-based pricing changed everything for us — if they forget, they pay less, and they self-select back.'),
    ],
  },
  {
    id: 't3_saas02',
    source: 'reddit',
    channel: 'r/startups',
    title: 'Stripe fees are eating 4% of revenue at small ticket sizes — alternatives?',
    body: 'Average order is $7. Between Stripe + currency conversion we lose ~4%. At our volume that is a real salary. What do micro-SaaS folks use?',
    author: 'tiny_ticket',
    score: 198,
    numComments: 56,
    commentDepth: 2,
    ageMinutes: 220,
    comments: [
      c('payments_nerd', 30, 0, 'At $7 ACV nothing beats Stripe meaningfully; the fixed 30c is your killer, not the %. Bundle into larger purchases.', [
        c('tiny_ticket', 7, 1, 'Yeah the 30c flat is the real pain. Considering credit packs.'),
      ]),
      c('eu_founder', 14, 0, 'Mollie is cheaper in EU for small tickets, worth a look.'),
    ],
  },
  {
    id: 't3_saas03',
    source: 'reddit',
    channel: 'r/Entrepreneur',
    title: 'Cold email is dead for B2B SaaS? My 3-month experiment',
    body: '',
    author: 'b2b_ops',
    score: 421,
    numComments: 133,
    commentDepth: 3,
    ageMinutes: 540,
    comments: [
      c('reply_guy', 55, 0, 'Not dead, just saturated. Deliverability is the whole game now — warm domains, tight lists.'),
      c('skeptic7', 19, 0, 'Define dead. We still close 5-figure deals from cold. Your list quality is probably the issue.'),
    ],
  },
  {
    id: 't3_saas04',
    source: 'reddit',
    channel: 'r/SaaS',
    title: 'Anyone else drowning in support tickets after adding AI features?',
    body: 'Shipped an AI assistant and support volume tripled — users expect magic, get confused, file tickets. Did AI features increase your support load?',
    author: 'support_swamped',
    score: 167,
    numComments: 49,
    commentDepth: 2,
    ageMinutes: 75,
    comments: [
      c('cx_lead', 28, 0, 'Yes. AI raises expectations faster than it meets them. We added confidence labels + "this may be wrong" and tickets dropped 30%.', [
        c('support_swamped', 9, 1, 'Confidence labels — smart. Trying that.'),
      ]),
    ],
  },
  {
    id: 't3_saas05',
    source: 'reddit',
    channel: 'r/startups',
    title: 'We open-sourced our core and revenue went UP — counterintuitive lessons',
    body: 'Everyone said open-sourcing the engine would kill our paid tier. Six months later MRR is up 40%. Here is what actually happened.',
    author: 'oss_founder',
    score: 503,
    numComments: 91,
    commentDepth: 2,
    ageMinutes: 1290,
    comments: [
      c('hnreader', 44, 0, 'Classic — OSS is distribution, the paid tier is the hosting/ops. Works when self-hosting is genuinely annoying.'),
    ],
  },
  {
    id: 't3_saas06',
    source: 'reddit',
    channel: 'r/SaaS',
    title: 'Pricing page A/B test: removing the cheapest tier raised conversions 22%',
    body: 'Counterintuitive but real. Dropping our $9 plan pushed people to $29 instead of away. Anchoring is wild.',
    author: 'price_tinkerer',
    score: 276,
    numComments: 63,
    commentDepth: 1,
    ageMinutes: 410,
    comments: [c('cro_pat', 33, 0, 'Decoy effect. Now add a "most popular" badge on $29 and watch it climb again.')],
  },
  // ── 以下默认作「待发现」池：discover 会陆续发现它们 ──
  {
    id: 't3_saas07',
    source: 'reddit',
    channel: 'r/SaaS',
    title: 'Building in public got us 0 customers but 10k followers — what went wrong?',
    body: 'Huge audience, no revenue. Followers love the journey but will not pay for the product. Anyone bridged this gap?',
    author: 'public_builder',
    score: 144,
    numComments: 38,
    commentDepth: 2,
    ageMinutes: 30,
    comments: [
      c('audience_skeptic', 22, 0, 'Followers of "building in public" want to BE you, not buy from you. Wrong audience for the product.'),
    ],
  },
  {
    id: 't3_saas08',
    source: 'reddit',
    channel: 'r/startups',
    title: 'Our biggest customer churned and took 30% of MRR — concentration risk is real',
    body: 'One logo was 30% of revenue. They got acquired, killed our contract. Lesson learned the hard way. How do you de-risk?',
    author: 'mrr_anxiety',
    score: 389,
    numComments: 77,
    commentDepth: 2,
    ageMinutes: 18,
    comments: [
      c('cfo_minded', 40, 0, 'No customer over 10% of MRR is the rule. Painful early, lifesaving later.'),
    ],
  },
  {
    id: 't3_saas09',
    source: 'reddit',
    channel: 'r/Entrepreneur',
    title: 'Free tier abusers are costing us more than they convert — kill it?',
    body: 'Our free tier is 90% of infra cost and 2% of conversions. Tempted to nuke it. Talk me out of it.',
    author: 'infra_bleeding',
    score: 231,
    numComments: 58,
    commentDepth: 1,
    ageMinutes: 8,
    comments: [c('plg_vet', 27, 0, 'Do not kill it, gate it. Cap the expensive operation, keep the cheap value. Free tier is your funnel.')],
  },
  {
    id: 'hn_42010',
    source: 'hackernews',
    channel: 'front',
    title: 'Show HN: I built a tool that turns Postgres into a realtime API in one command',
    body: '',
    author: 'pg_hacker',
    score: 612,
    numComments: 204,
    commentDepth: 3,
    ageMinutes: 50,
    comments: [
      c('dbweenie', 88, 0, 'How does this handle row-level security? That is where every "instant API" tool falls over.', [
        c('pg_hacker', 31, 1, 'RLS is passed through; we generate policies from your existing roles. Demo in the README.'),
      ]),
    ],
  },
  {
    id: 'hn_42011',
    source: 'hackernews',
    channel: 'new',
    title: 'Ask HN: Why is every dev tool now a "platform"? I just want a CLI',
    body: 'Feels like every tool wants to be an ecosystem with a dashboard and a billing portal. Whatever happened to a sharp single-purpose CLI?',
    author: 'unix_greybeard',
    score: 287,
    numComments: 159,
    commentDepth: 2,
    ageMinutes: 12,
    comments: [
      c('vc_logic', 45, 0, 'Because CLIs do not have expansion revenue. Platforms do. Follow the money.'),
    ],
  },
  {
    id: 'rss_tc_88',
    source: 'rss',
    channel: 'TechCrunch',
    title: 'Vertical SaaS is quietly out-earning horizontal SaaS, new data shows',
    body: 'A fresh report finds niche, industry-specific SaaS retains customers far longer than broad horizontal tools — and commands higher pricing.',
    author: 'TechCrunch',
    score: 0,
    numComments: 0,
    commentDepth: 0,
    ageMinutes: 140,
    comments: [],
  },
];
