CREATE TYPE "public"."intensity" AS ENUM('HIGH', 'MEDIUM', 'LOW');--> statement-breakpoint
CREATE TYPE "public"."job_status" AS ENUM('queued', 'running', 'succeeded', 'failed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."job_trigger" AS ENUM('auto', 'manual');--> statement-breakpoint
CREATE TYPE "public"."provider_kind" AS ENUM('anthropic', 'openai', 'deepseek');--> statement-breakpoint
CREATE TYPE "public"."triage_status" AS ENUM('pending', 'shortlisted', 'archived');--> statement-breakpoint
CREATE TABLE "analysis_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "analysis_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" text NOT NULL,
	"provider_id" integer,
	"model" text NOT NULL,
	"trigger" "job_trigger" NOT NULL,
	"status" "job_status" NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"error" text,
	"enqueued_at" bigint NOT NULL,
	"started_at" bigint,
	"finished_at" bigint,
	"heartbeat_at" bigint
);
--> statement-breakpoint
CREATE TABLE "app_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" text PRIMARY KEY NOT NULL,
	"post_id" text NOT NULL,
	"parent_id" text,
	"author" text,
	"body" text NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"depth" integer DEFAULT 0 NOT NULL,
	"created_utc" bigint NOT NULL,
	"fetched_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "insights" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "insights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" text NOT NULL,
	"source" text DEFAULT 'reddit' NOT NULL,
	"subreddit" text NOT NULL,
	"post_title" text NOT NULL,
	"permalink" text,
	"model" text NOT NULL,
	"intensity" "intensity" NOT NULL,
	"pain_points" jsonb NOT NULL,
	"opportunities" jsonb NOT NULL,
	"tags" jsonb NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "model_providers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_providers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" "provider_kind" NOT NULL,
	"label" text NOT NULL,
	"api_key" text NOT NULL,
	"base_url" text,
	"model" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" bigint NOT NULL,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" text PRIMARY KEY NOT NULL,
	"source" text DEFAULT 'reddit' NOT NULL,
	"subreddit" text NOT NULL,
	"title" text NOT NULL,
	"author" text,
	"selftext" text DEFAULT '' NOT NULL,
	"url" text,
	"permalink" text,
	"score" integer DEFAULT 0 NOT NULL,
	"num_comments" integer DEFAULT 0 NOT NULL,
	"created_utc" bigint NOT NULL,
	"fetched_at" bigint NOT NULL,
	"comment_pass" integer DEFAULT 0 NOT NULL,
	"comments_fetched_at" bigint,
	"comments_changed_at" bigint,
	"export_locked_at" bigint,
	"analyzed_at" bigint,
	"analyze_attempts" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sync_ops" (
	"op_id" text PRIMARY KEY NOT NULL,
	"device_id" text NOT NULL,
	"type" text NOT NULL,
	"target_id" integer NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" bigint NOT NULL,
	"applied_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "triage" (
	"insight_id" integer PRIMARY KEY NOT NULL,
	"status" "triage_status" DEFAULT 'pending' NOT NULL,
	"rating" integer,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	"updated_at" bigint NOT NULL,
	CONSTRAINT "triage_rating_range" CHECK ("triage"."rating" BETWEEN 1 AND 5)
);
--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_jobs_status" ON "analysis_jobs" USING btree ("status","enqueued_at");--> statement-breakpoint
CREATE INDEX "idx_jobs_post" ON "analysis_jobs" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX "idx_comments_post" ON "comments" USING btree ("post_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_insights_post" ON "insights" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX "idx_insights_subreddit" ON "insights" USING btree ("subreddit");--> statement-breakpoint
CREATE INDEX "idx_insights_intensity" ON "insights" USING btree ("intensity");--> statement-breakpoint
CREATE INDEX "idx_posts_subreddit" ON "posts" USING btree ("subreddit");--> statement-breakpoint
CREATE INDEX "idx_posts_created" ON "posts" USING btree ("created_utc");--> statement-breakpoint
CREATE INDEX "idx_posts_pending" ON "posts" USING btree ("analyzed_at","comment_pass");